import Head from 'next/head';
import { useState } from 'react';

import Navbar from '../components/Navbar';
import Intro from '../components/Intro';
import Services from '../components/Services';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
      <div>
        <Head>
          <title>PortFolio - Vishal Kumar Sharma</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='apple-touch-icon' sizes='180x180' href='/apple-touch-icon.png' />
          <link rel='icon' type='image/png' sizes='32x32' href='/favicon-32x32.png' />
          <link rel='icon' type='image/png' sizes='16x16' href='/favicon-16x16.png' />
          <link rel='manifest' href='/site.webmanifest'></link>
        </Head>
        <main className='bg-dark font-Comfortaa'>
          <Navbar />
          <Intro />
          <Services />
        </main>
      </div>
    </>
  );
}
