import Head from 'next/head';
import { useState } from 'react';

import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillLinkedin } from 'react-icons/ai';
import Image from 'next/image';
import animoji from '../public/animoji.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import logo from '../public/logo.svg';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
      <div className={darkMode ? 'dark' : ''}>
        <Head>
          <title>PortFolio - Vishal Kumar Sharma</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='apple-touch-icon' sizes='180x180' href='/apple-touch-icon.png' />
          <link rel='icon' type='image/png' sizes='32x32' href='/favicon-32x32.png' />
          <link rel='icon' type='image/png' sizes='16x16' href='/favicon-16x16.png' />
          <link rel='manifest' href='/site.webmanifest'></link>
        </Head>
        <main className='px-5 md:px-20 bg-gray-900 font-Comfortaa '>
          <section className='pt-5 flex justify-between align-middle'>
            <Image src={logo} className='w-20 h-20' />
            <nav className='py-5 mb-12 flex justify-between align-middle'>
              <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 h-10 font-bold' href='resume.pdf' target='_blank'>
                Resume
              </a>
            </nav>
          </section>
          <section className='min-h-screen'>
            <div className='mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 relative overflow-hidden md:h-80 md:w-80'>
              <Image src={animoji} fill={true} style={{ objectFit: 'cover' }} />
            </div>
            <div className='text-center p-5'>
              <h2 className='text-3xl py-2 text-teal-600 font-medium md:text-6xl'>
                <span className='font-DancingScript'>I'm</span> Vishal Kumar Sharma
              </h2>
              <h3 className='text-2xl py-2 md:text-3xl text-white'>Developer and Designer.</h3>
              <p className='text-md py-5 leading-8 text-gray-400 md:text-xl max-w-lg mx-auto '>INTRO TEXT</p>
            </div>
            {/* <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
              <AiFillLinkedin />
            </div> */}
          </section>

          <section>
            <div>
              <h3 className='text-3xl py-1'>Services I offer</h3>
              <p className='text-md py-2 leading-8 text-gray-800'>TEXT</p>
            </div>
            <div className='lg:flex gap-10'>
              <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1'>
                <Image className='mx-auto' src={design} width={100} height={100} />
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
                <p>TEXT</p>

                <h4 className='py-4 text-teal-600'>Tools I use</h4>
                <p className='text-gray-800 py-1 '>TEXT</p>
                <p className='text-gray-800 py-1 '>TEXT</p>
                <p className='text-gray-800 py-1 '>TEXT</p>
                <p className='text-gray-800 py-1 '>TEXT</p>
              </div>

              <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1'>
                <Image className='mx-auto' src={code} width={100} height={100} />
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
                <p>TEXT</p>

                <h4 className='py-4 text-teal-600'>Tools I use</h4>
                <p className='text-gray-800 py-1 '>TEXT</p>
                <p className='text-gray-800 py-1 '>TEXT</p>
                <p className='text-gray-800 py-1 '>TEXT</p>
                <p className='text-gray-800 py-1 '>TEXT</p>
              </div>

              <div className='text-center shadow-lg p-10 rounded-xl my-10 flex-1'>
                <Image className='mx-auto' src={consulting} width={100} height={100} />
                <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
                <p>TEXT</p>

                <h4 className='py-4 text-teal-600'>Tools I use</h4>
                <p className='text-gray-800 py-1 '>TEXT</p>
                <p className='text-gray-800 py-1 '>TEXT</p>
                <p className='text-gray-800 py-1 '>TEXT</p>
                <p className='text-gray-800 py-1 '>TEXT</p>
              </div>
            </div>
          </section>
          <section>
            <div>
              <h3 className='text-3xl py-1'>Portfolio</h3>
              <p className='text-md py-2 leading-8 text-gray-800'>TEXT</p>
            </div>
            <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
              <div className='basis-1/3 flex-1'>
                <Image className='rounded-lg object-cover ' width={'100%'} height={'100%'} src={web1} />
              </div>
              <div className='basis-1/3 flex-1'>
                <Image className='rounded-lg object-cover ' width={'100%'} height={'100%'} src={web2} />
              </div>
              <div className='basis-1/3 flex-1'>
                <Image className='rounded-lg object-cover ' width={'100%'} height={'100%'} src={web3} />
              </div>
              <div className='basis-1/3 flex-1'>
                <Image className='rounded-lg object-cover ' width={'100%'} height={'100%'} src={web4} />
              </div>
              <div className='basis-1/3 flex-1'>
                <Image className='rounded-lg object-cover ' width={'100%'} height={'100%'} src={web5} />
              </div>
              <div className='basis-1/3 flex-1'>
                <Image className='rounded-lg object-cover ' width={'100%'} height={'100%'} src={web6} />
              </div>
            </div>
          </section>
        </main>
      </div>
    </>
  );
}
